set_battery_charge_state:
  name: battery_sim.set_battery_charge_state.name
  description: battery_sim.set_battery_charge_state.description
  fields:
    device_id:
      name: battery_sim.set_battery_charge_state.fields.device_id.name
      description: battery_sim.set_battery_charge_state.fields.device_id.description
      required: true
      selector:
        device:
          integration: battery_sim
    charge_state:
      name: battery_sim.set_battery_charge_state.fields.charge_state.name
      description: battery_sim.set_battery_charge_state.fields.charge_state.description
      required: true
      selector:
        number:
          mode: box
          min: 0
          max: 10000
          step: 0.1

set_battery_cycles:
  name: battery_sim.set_battery_cycles.name
  description: battery_sim.set_battery_cycles.description
  fields:
    device_id:
      name: battery_sim.set_battery_cycles.fields.device_id.name
      description: battery_sim.set_battery_cycles.fields.device_id.description
      required: true
      selector:
        device:
          integration: battery_sim
    battery_cycles:
      name: battery_sim.set_battery_cycles.fields.battery_cycles.name
      description: battery_sim.set_battery_cycles.fields.battery_cycles.description
      required: true
      selector:
        number:
          mode: box
          min: 0
          max: 50000
          step: 1

set_stored_energy_value:
  name: battery_sim.set_stored_energy_value.name
  description: battery_sim.set_stored_energy_value.description
  fields:
    device_id:
      name: battery_sim.set_stored_energy_value.fields.device_id.name
      description: battery_sim.set_stored_energy_value.fields.device_id.description
      required: true
      selector:
        device:
          integration: battery_sim
    stored_energy_value:
      name: battery_sim.set_stored_energy_value.fields.stored_energy_value.name
      description: battery_sim.set_stored_energy_value.fields.stored_energy_value.description
      required: true
      selector:
        number:
          mode: box
          step: 0.01
