name: Run tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install test dependencies
        run: pip install -r requirements_test.txt
      - name: Run tests
        run: pytest --cov=custom_components.battery_sim --cov-report=term-missing
